// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5o0PX7Hy3Wy2t7tpnkxRjdYspYCSWWPo',
    appId: '1:655130167888:web:611189d8601950813d9f55',
    messagingSenderId: '655130167888',
    projectId: 'kgarage-151b3',
    authDomain: 'kgarage-151b3.firebaseapp.com',
    storageBucket: 'kgarage-151b3.firebasestorage.app',
    measurementId: 'G-V9XLT35RZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrG4X8DhJofaA3w2_EKq_iKik49Ab-9U',
    appId: '1:655130167888:android:334a4b1f7da8f2023d9f55',
    messagingSenderId: '655130167888',
    projectId: 'kgarage-151b3',
    storageBucket: 'kgarage-151b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB44hcsaJuXjnKnU3Tsmuj9pdLfG7y0gQ',
    appId: '1:655130167888:ios:c6485798e186d0bb3d9f55',
    messagingSenderId: '655130167888',
    projectId: 'kgarage-151b3',
    storageBucket: 'kgarage-151b3.firebasestorage.app',
    iosBundleId: 'com.example.kgarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB44hcsaJuXjnKnU3Tsmuj9pdLfG7y0gQ',
    appId: '1:655130167888:ios:c6485798e186d0bb3d9f55',
    messagingSenderId: '655130167888',
    projectId: 'kgarage-151b3',
    storageBucket: 'kgarage-151b3.firebasestorage.app',
    iosBundleId: 'com.example.kgarage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5o0PX7Hy3Wy2t7tpnkxRjdYspYCSWWPo',
    appId: '1:655130167888:web:cc4d95cdb9f6f5b43d9f55',
    messagingSenderId: '655130167888',
    projectId: 'kgarage-151b3',
    authDomain: 'kgarage-151b3.firebaseapp.com',
    storageBucket: 'kgarage-151b3.firebasestorage.app',
    measurementId: 'G-MXEY9SP9J0',
  );
}
